### PR TITLE
Revamped filtered ThermoML data

### PR DESCRIPTION
**Pull request by bmanubay**
Added headers to the count csv and SMILES formulae where appropriate

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

This could really use some `README.md` files in each directory that explain what information is contained in the files that appear in these directory and the naming schemes for these files, as well as a bit of a summary of what protocol you used in the main `README.md`.  Could you add this, and then we can merge?

**Comment by bmanubay** [comment]
Hey @jchodera, I think I've made all the necessary additions that you wanted. Let me know if I should revise anything to fit whatever style you prefer. Do I need to make another merge request or no?

**Comment by jchodera** [comment]
Thanks!  The `README.md` files are very helpful!

**Comment by jchodera** [comment]
OK, I've merged this now!

**Pull request merged**
