### PR TITLE
Updates to README.md; add CIB molecule set.

### PR DESCRIPTION
**Pull request by davidlmobley**
Updating README.md and files to add Christopher Bayly's molecule set. 

Here is an e-mail he sent describing it:

> Attached is AlkEthOH_distrib2016may01.tar.gz, containing the fruit of my efforts to come up with a toy dataset for alkanes, alcohols, and ethers as per our workplan.
> 
> I call the set AlkEthOH.
> 
> I have tried to explain everything in the README.txt contained in the distribution.
> 
> Peroxides, 3-membered rings, and ketals were removed from the initial sets of 1303 acyclic molecules and 1156 cyclic molecules, leaving:
> 913 acyclic molecules in AlkEthOH_chain_filt1.smi
> 1036 cyclic molecules in AlkEthOH_rings_filt1.smi
> 
> A single conformer of all of these is amberized, with a well-described workflow and associated python scripts.
> 
> The parm@Frosst subset is given as frcmod.Frosst_AlkEthOH; it is not small but it is the smallest possible. The tleap leaprc file leaprc.Frosst_AlkEthOH needed to make it work is also included. For example, for AlkEthOH_r21.mol2, run:

`tleap -f leaprc.Frosst_AlkEthOH -f AlkEthOH_r21.leap_in`

> where AlkEthOH_r21.leap_in contains:
> 
> ```
> lig = loadMol2 AlkEthOH_r21.mol2
> saveAmberParm lig AlkEthOH_r21.top AlkEthOH_r21.crd
> quit
> ```
> 
> I am hoping this gives you what you need to get started. Let me know if you have questions. Sorry I can't distribute xpat at this time.
> 
> Still to do: cobble together a hand-guessed SMIRFF file corresponding to frcmod.Frosst_AlkEthOH. I will do this asap... this week.

### CODE REVIEW

**Comment by jchodera** [comment]
This is great.  I can easily automate the computation of all their energies with this.

Should we store the computed MM energies in an annotated SDF file?

**Comment by davidlmobley** [comment]
Yes, we absolutely should! Or any other easy-to-use format...

Thanks.

On Mon, May 2, 2016 at 3:10 PM, John Chodera notifications@github.com
wrote:

> This is great. I can easily automate the computation of all their energies
> with this.
> 
> Should we store the computed MM energies in an annotated SDF file?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/2#issuecomment-216380628

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Also, @jchodera - let me know if you'd prefer I automate that, as I'm probably less swamped than you. I've done the `openmm` aspect less frequently but I think I can manage it, i.e. by adapting this test: https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_utils.py#L70 which compares OpenMM energies for systems created from GROMACS and AMBER parameters which ought to be identical. (The aspect of reading the .frcmod and .mol2 files to get AMBER parameters is trivial).

**Comment by davidlmobley** [comment]
Added Bayly SMIRFF/SMARFF prototype from e-mail, and associated supporting files.

I'd forgotten to merge this so I'll do so now.

**Pull request merged**
