### PR TITLE
Add generated amber input files (.top, .crd, .leap_in, .mol2) as an archive, and fix script for generating

### PR DESCRIPTION
**Pull request by vtlim**
addressing #15 with script oebToAmberMol2TopCrd.py

### CODE REVIEW

**Comment by vtlim** [comment]
@davidlmobley

**Comment by davidlmobley** [comment]
So, what about removing the large set of individual output files and replacing with a single `.tar.gz`, @vtlim ? This makes it a bit hard to see what's changed in the diff ("files changed" at top) and also presumably it's going to be a lot slower to clone this way than if it's in an archive. 

You should be able to achieve this - if it sounds OK to you - by creating an archive out of the individual files, adding it, and removing the individual files (i.e. `git rm`)

**Comment by davidlmobley** [comment]
(Then you just make a new commit and push with those changes and it will update this PR, @vtlim )

**Comment by jchodera** [comment]
Do we even _want_ to check these files in? Compared to the simulations that will produce the estimated physical properties we will use as input, these files should essentially take no time to generate on the fly. Why not just check in a script that algorithmically generates them in the process of running simulations to compute physical properties?

**Comment by davidlmobley** [comment]
I think that's checked in as well.

On Thu, Jun 23, 2016 at 9:12 PM, John Chodera notifications@github.com
wrote:

> Do we even _want_ to check these files in? Compared to the simulations
> that will produce the estimated physical properties we will use as input,
> these files should essentially take no time to generate on the fly. Why not
> just check in a script that algorithmically generates them in the process
> of running simulations to compute physical properties?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/17#issuecomment-228254167,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYe6aCAzgQazqX7IXTlVjNBFLwN7Sks5qO1kggaJpZM4I9YWh
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
I do actually think though on occasion it will be helpful to me to have
these on hand - i.e. if I want to look at populations of different
parm@frosst types or something, I'll already have the files to do so. So
unless you see a big downside I'd rather have both the files and the script
as well. :) If you see a downside I can have her share them with me in a
different way, though that seems to add an unnecessary extra step.

On Thu, Jun 23, 2016 at 9:12 PM, John Chodera notifications@github.com
wrote:

> Do we even _want_ to check these files in? Compared to the simulations
> that will produce the estimated physical properties we will use as input,
> these files should essentially take no time to generate on the fly. Why not
> just check in a script that algorithmically generates them in the process
> of running simulations to compute physical properties?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/17#issuecomment-228254167,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYe6aCAzgQazqX7IXTlVjNBFLwN7Sks5qO1kggaJpZM4I9YWh
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
> I do actually think though on occasion it will be helpful to me to have
> these on hand - i.e. if I want to look at populations of different
> parm@frosst types or something, I'll already have the files to do so. 

You can generate a single typed mol2 or SDF file containing all the typed molecules.

For everything else, we could have a single script or method call to regenerate the files we need.

> So unless you see a big downside I'd rather have both the files and the script
> as well. :) If you see a downside I can have her share them with me in a
> different way, though that seems to add an unnecessary extra step.

There is definitely a big downside to adding 8000 files to this repo. Let's not do that.

Depending on how big the tarball is, it may not be a good idea to include that either. Things get really slow when the repo gets to ~1GB in size...

**Comment by davidlmobley** [comment]
@jchodera - FYI, the archived set of files is only 5 MB, so we believe it's worth including the whole set since it does take a few minutes to re-generate them. Vickie ( @vtlim ) is polishing the script used for generating these so we can finish this off (originally it required hand manipulation for a couple of special cases Chris Bayly had added to the set at the last minute).

**Comment by jchodera** [comment]
Sure, 5 MB is fine.

An extra unintended file seems like it was added:

```
Model-Systems/AlkEthOH_distrib/files_for_c1302/.oebToAmberMol2TopCrd_edited.py.swp
```

**Comment by davidlmobley** [comment]
OK, I checked this, @vtlim , and it seems to be in good shape so I'll merge. Thanks!

**Pull request merged**
