### PR TITLE
Interesting Mixtures

### PR DESCRIPTION
**Pull request by bmanubay**
Added Python code and generated csv for finding data point counts of interesting (not alkane-alkane) mixtures across all binary properties

### CODE REVIEW

**Comment by davidlmobley** [comment]
Looks like interesting mixtures indeed. Nice work. I had an outstanding PR
open so I just merged it, so can you update one more time and then ping me
again and we can merge?

Thanks.

On Wed, May 11, 2016 at 1:43 PM, bmanubay notifications@github.com wrote:

> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7
> Commit Summary
> - Interesting mixtures
> - Merge remote-tracking branch 'upstream/master'
> - Interesting mixtures
> 
> File Changes
> - _M_ Initial Molecule Choices/allcomp_counts_diverse.csv
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7/files#diff-0
>   (2)
> - _A_ Initial Molecule Choices/mix_counts_interesting.csv
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7/files#diff-1
>   (181)
> - _M_ Initial Molecule Choices/purecomp_counts_all.csv
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7/files#diff-2
>   (2)
> - _M_ Python/binsrch.py
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7/files#diff-3
>   (2)
> - _A_ Python/mixchk.py
>   https://github.com/open-forcefield-group/open-forcefield-data/pull/7/files#diff-4
>   (46)
> 
> Patch Links:
> 
>    -
>    https://github.com/open-forcefield-group/open-forcefield-data/pull/7.patch
>    -
>    https://github.com/open-forcefield-group/open-forcefield-data/pull/7.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/7

## 

David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by davidlmobley** [comment]
Sorry, by "update" I mean "git pull ..." to merge, then commit/push. This time the changes are orthogonal to yours so it should be a super easy merge.

**Comment by bmanubay** [comment]
Everything is ready to go @davidlmobley !

**Comment by jchodera** [comment]
Awesome!

**Pull request merged**
