### PR TITLE
Update smartsDepict.ipynb for SMARFF with angle energies

### PR DESCRIPTION
**Pull request by davidlmobley**
Updated ipython notebook with angle energies from John Chodera, updated so it will still run when applied to non-angle terms. 

Also made a minor fix to the README.txt for SMIRFF prototype at the same time.

### CODE REVIEW

**Comment by jchodera** [comment]
Weird---I don't see any energies in the output.  Does this mean it is no longer working?

**Comment by davidlmobley** [comment]
Er, maybe I forgot and left it so it's set to display a torsion. Lemme
check.

On Wed, May 11, 2016 at 2:09 PM, John Chodera notifications@github.com
wrote:

> Weird---I don't see any energies in the output. Does this mean it is no
> longer working?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/5#issuecomment-218590974

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Sorry about that. Just uncomment the one line and comment out the other:

> #Smarts = '[#6X4]-[#6X4]-[#8X2]'  #Angle query
> Smarts = '[#6X4]-[#6X4]-[#6X4]-[#6X4]' #Torsional query

**Comment by davidlmobley** [comment]
(Your code wouldn't run if one specified a torsion, so I fixed it so it would run - but not print any energies - until I can do #6 )

**Comment by jchodera** [comment]
Thanks!

Are we really sure this belongs in `open-forcefield-data`?  What about `open-forcefield-toymodels`?

**Comment by davidlmobley** [comment]
I'm fine with putting it somewhere like that, yes.

On Wed, May 11, 2016 at 2:14 PM, John Chodera notifications@github.com
wrote:

> Thanks!
> 
> Are we really sure this belongs in open-forcefield-data? What about
> open-forcefield-toymodels?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/open-forcefield-group/open-forcefield-data/pull/5#issuecomment-218592379

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Pull request merged**
